version: "3"
services:
  web_app:
    container_name: web_app
    image: web_app
    build:
      context: ./web/
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - ./web/:/usr/cineclub:delegated
      - node_modules_web:/node_modules
    depends_on:
      - api_server
    networks:
      - frontend
  api_server:
    container_name: api_server
    image: api_server
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3001:3001"
    volumes:
      - ./api/:/usr/cineclub:delegated
      - node_modules_api:/node_modules
    depends_on:
      - mongo
    networks:
      - frontend
      - backend
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
volumes:
  mongo-data:
    driver: local
  node_modules_web:
    driver: local
  node_modules_api:
    driver: local
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
