version: "3"
services:
  web-app:
    image: web-app
    build:
      context: ./web/
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    networks:
      - web-api-network
    links:
      - api-server
  api-server:
    image: api-server
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3001:3001"
    networks:
      - web-api-network
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
networks:
  web-api-network:
    driver: bridge
