version: "3"
services:
  cineclub-web-app:
    image: cineclub-web-app
    build:
      context: ./web/
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - ./web/:/usr/cineclub:delegated
      - node_modules:/node_modules
    links:
      - cineclub-api-server
  cineclub-api-server:
    image: cineclub-api-server
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3001:3001"
    volumes:
      - ./api/:/usr/cineclub:delegated
      - node_modules:/node_modules
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
volumes:
  mongo-data:
    driver: local
  node_modules:
    driver: local
