version: "3"
services:
  web_app:
    container_name: web_app
    image: cineclub_web_app
    build:
      context: ./web/
      dockerfile: Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        touch .env
        echo "PORT=${WEB_PORT}" > .env
        echo "REACT_APP_API_HOST=${API_HOST}" >> .env
        echo "REACT_APP_API_PORT=${API_PORT}" >> .env
        npm run debug
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      - NODE_ENV=development
      - API_HOST
      - API_PORT
      - WEB_PORT
    volumes:
      - ./web/:/usr/web:delegated
      - node_modules_web:/node_modules
    depends_on:
      - api_server
    networks:
      - frontend
  api_server:
    container_name: api_server
    image: cineclub_api_server
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_SECRET
      - API_PORT
      - DB_HOST=mongo
      - DB_PORT
      - DB_NAME
    volumes:
      - ./api/:/usr/api:delegated
      - node_modules_api:/node_modules
    depends_on:
      - mongo
    networks:
      - frontend
      - backend
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mongo_data_dev:/data/db
      - mongo_config:/data/configdb
    networks:
      - backend
volumes:
  mongo_data_dev:
    driver: local
  mongo_config:
    driver: local
  node_modules_web:
    driver: local
  node_modules_api:
    driver: local
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
